In [13]:
import pandas as pd 
import os 
import logging 
import traceback
from basicprocess import create_folder, outputlog
from TDXdataframe import read_businfo_xml

In [ ]:
def get_taipeibusreport(odspath):

    logging.info("開始讀取台北市營運月報")
    logging.info(f"台北市公車營運月報的原始檔案為{odspath}")

    sheet_names = pd.ExcelFile(odspath).sheet_names
    dfs = []
    for sheet in sheet_names:
        odsdf = pd.read_excel(odspath, sheet_name=sheet, engine='odf')
        odsdf['Time'] = sheet
        dfs.append(odsdf)

    df = pd.concat(dfs, ignore_index=True)

    logging.info("台北市營運月報整併完成")
    

    df['年'] = df['Time'].str[:3].astype(int) + 1911
    df['月'] = df['Time'].str[3:].astype(int)
    # df['資料時間'] = pd.to_datetime(df['年'].astype(str) + '-' + df['月'].astype(str)).dt.to_period('M')
    df['資料時間'] = pd.to_datetime(
        df['年'].astype(str) + '-' + df['月'].astype(str).str.zfill(2),
        format='%Y-%m',
        errors='raise').dt.to_period('M')

    cols = ['資料時間'] + [c for c in df.columns if c not in ['年', '月', 'Time', '資料時間']]
    df = df.reindex(columns=cols)

    logging.info("輸出指定格式")

    rename_dist = {'資料時間':'Month',
                '客運業者':'OperatorName', 
                '路線代碼':'RouteID', 
                '路線別':'RouteName', 
                '總班次':'Shifts', 
                '總載客人次':'Population',
                '總行駛里程':'Miles',
                '延人公里':'PaxKm', 
                '總營收': 'Revenue'}
    df = df[list(rename_dist)]
    df = df.rename(columns = rename_dist)

    return df

In [16]:
dfinfo = read_businfo_xml(r'D:\B-Project\2025\6800\Technical\12票證資料\TicketAnalysis\00_TDX資料下載\03公車路線營運資料\市區公車路線營運資料_臺北市_2025-12-16.xml')

In [18]:
dfinfo

,RouteUID,RouteID,HasSubRoutes,Operators_json,OperatorID_first,OperatorNameZh_first,OperatorNameEn_first,OperatorCode_first,OperatorNo_first,AuthorityID,...,DestinationStopNameEn,TicketPriceDescriptionZh,TicketPriceDescriptionEn,FareBufferZoneDescriptionZh,FareBufferZoneDescriptionEn,RouteMapImageUrl,City,CityCode,UpdateTime,VersionID
0,TPE10132,10132,True,"[{""OperatorID"": ""100"", ""OperatorNameZh"": ""臺北客運...",100,臺北客運,"Taipei Bus Co., Ltd.",TaipeiBus,1407,004,...,Ximen,一段票,1 segment,None,None,https://ebus.gov.taipei/MapOverview?nid=010002...,Taipei,TPE,2025-12-16T14:51:04+08:00,6521
1,TPE10132,10132,True,"[{""OperatorID"": ""100"", ""OperatorNameZh"": ""臺北客運...",100,臺北客運,"Taipei Bus Co., Ltd.",TaipeiBus,1407,004,...,Ximen,一段票,1 segment,None,None,https://ebus.gov.taipei/MapOverview?nid=010002...,Taipei,TPE,2025-12-16T14:51:04+08:00,6521
2,TPE10142,10142,True,"[{""OperatorID"": ""100"", ""OperatorNameZh"": ""臺北客運...",100,臺北客運,"Taipei Bus Co., Ltd.",TaipeiBus,1407,004,...,Taipei City Hall,兩段票,2 segments,景美女中-石壁坑,None,https://ebus.gov.taipei/MapOverview?nid=011300...,Taipei,TPE,2025-12-16T14:51:04+08:00,6521
3,TPE10142,10142,True,"[{""OperatorID"": ""100"", ""OperatorNameZh"": ""臺北客運...",100,臺北客運,"Taipei Bus Co., Ltd.",TaipeiBus,1407,004,...,Taipei City Hall,兩段票,2 segments,景美女中-石壁坑,None,https://ebus.gov.taipei/MapOverview?nid=011300...,Taipei,TPE,2025-12-16T14:51:04+08:00,6521
4,TPE10142,10142,True,"[{""OperatorID"": ""100"", ""OperatorNameZh"": ""臺北客運...",100,臺北客運,"Taipei Bus Co., Ltd.",TaipeiBus,1407,004,...,Taipei City Hall,兩段票,2 segments,景美女中-石壁坑,None,https://ebus.gov.taipei/MapOverview?nid=011300...,Taipei,TPE,2025-12-16T14:51:04+08:00,6521
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1161,TPE19755,19755,False,"[{""OperatorID"": ""800"", ""OperatorNameZh"": ""大都會客...",800,大都會客運,"Metropolitan Bus Co., Ltd.",MetropolitanBus,0303,004,...,Taipei Main Sta.,二段票,2 segments,None,None,https://ebus.gov.taipei/MapOverview?nid=016300...,Taipei,TPE,2025-12-16T14:51:04+08:00,6521
1162,TPE19759,19759,True,"[{""OperatorID"": ""5300"", ""OperatorNameZh"": ""光華巴...",5300,光華巴士,"Kuang-Hua Bus Co., Ltd.",KuangHuaBus.,0601,004,...,Soochow U. Downtown Campus,二段票,2 segments,捷運士林站(中正)-士林區行政中心(中正),MRT Shilin Sta. (Zhongzheng)-Shilin Admin. Cen...,https://ebus.gov.taipei/MapOverview?nid=015200...,Taipei,TPE,2025-12-16T14:51:04+08:00,6521
1163,TPE19759,19759,True,"[{""OperatorID"": ""5300"", ""OperatorNameZh"": ""光華巴...",5300,光華巴士,"Kuang-Hua Bus Co., Ltd.",KuangHuaBus.,0601,004,...,Soochow U. Downtown Campus,二段票,2 segments,捷運士林站(中正)-士林區行政中心(中正),MRT Shilin Sta. (Zhongzheng)-Shilin Admin. Cen...,https://ebus.gov.taipei/MapOverview?nid=015200...,Taipei,TPE,2025-12-16T14:51:04+08:00,6521
1164,TPE810,810,True,"[{""OperatorID"": ""800"", ""OperatorNameZh"": ""大都會客...",800,大都會客運,"Metropolitan Bus Co., Ltd.",MetropolitanBus,0303,004,...,Veterans General Hospital,兩段票,2 segments,民權松江路口-銘傳大學,Minquan and Songjiang Lntersection-Mingchuan U.),https://ebus.gov.taipei/MapOverview?nid=016100...,Taipei,TPE,2025-12-16T14:51:04+08:00,6521
1165,TPE810,810,True,"[{""OperatorID"": ""800"", ""OperatorNameZh"": ""大都會客...",800,大都會客運,"Metropolitan Bus Co., Ltd.",MetropolitanBus,0303,004,...,Veterans General Hospital,兩段票,2 segments,民權松江路口-銘傳大學,Minquan and Songjiang Lntersection-Mingchuan U.),https://ebus.gov.taipei/MapOverview?nid=016100...,Taipei,TPE,2025-12-16T14:51:04+08:00,6521

In [17]:
dfinfo.columns

Index(['RouteUID', 'RouteID', 'HasSubRoutes', 'Operators_json',
       'OperatorID_first', 'OperatorNameZh_first', 'OperatorNameEn_first',
       'OperatorCode_first', 'OperatorNo_first', 'AuthorityID', 'ProviderID',
       'SubRouteUID', 'SubRouteID', 'OperatorIDs', 'SubRouteNameZh',
       'SubRouteNameEn', 'Headsign', 'HeadsignEn', 'Direction', 'FirstBusTime',
       'LastBusTime', 'HolidayFirstBusTime', 'HolidayLastBusTime',
       'SubDepartureStopNameZh', 'SubDepartureStopNameEn',
       'SubDestinationStopNameZh', 'SubDestinationStopNameEn', 'BusRouteType',
       'RouteNameZh', 'RouteNameEn', 'DepartureStopNameZh',
       'DepartureStopNameEn', 'DestinationStopNameZh', 'DestinationStopNameEn',
       'TicketPriceDescriptionZh', 'TicketPriceDescriptionEn',
       'FareBufferZoneDescriptionZh', 'FareBufferZoneDescriptionEn',
       'RouteMapImageUrl', 'City', 'CityCode', 'UpdateTime', 'VersionID'],
      dtype='object')

In [20]:
df

,Month,OperatorName,RouteID,RouteName,Shifts,Population,Miles,PaxKm,Revenue
0,2024-01,欣欣客運,10,1,3900,168591,46782,1618474,3974875
1,2024-01,首都客運,2000,2,840,20564,10332,101175,484840
2,2024-01,欣欣客運,180,18,2556,73769,29355,681626,1739246
3,2024-01,首都客運,2101,21,440,9174,3938,65686,216292
4,2024-01,首都客運,2600,26,308,5246,3388,46165,123681
...,...,...,...,...,...,...,...,...,...
7627,2025-06,東南客運,1002,小2區間,1992,13766,10956,60570,349939
7628,2025-06,東南客運,829,紅29,1836,56174,31028,759472,1427961
7629,2025-06,東南客運,1010,小10區間,1116,15665,11572,129949,398211
7630,2025-06,東南客運,11,小11路,1236,9423,11708,71410,239530
7631,2025-06,東南客運,12,小12路,420,4658,7359,65292,118402

In [ ]:
'''Setup & Main Execution'''
# 00_Setup 所有全域函數
logfile = os.path.abspath(os.path.join(os.getcwd(), '..', 'Log', '04_營運月報整理.log'))
if os.path.exists(logfile):
    os.remove(logfile)
    
logging.basicConfig(
    filename=logfile,
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s"
)


def main():
    
    df = get_taipeibusreport(r"D:\OneDrive - 鼎漢國際工程顧問股份有限公司\部門空間管理者8\B-6812-修訂臺北都會區整體路網\Technical\18票證月報資料\04臺北\01公運處\附2-項目(二)臺北市營運資料(市區公車)v1.ods")
    
if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        logging.error("main() 執行失敗：%s", e)  
        logging.error("Traceback:\n%s", traceback.format_exc())
    
    outputlog(logfile=logfile)